/**
 * Type transformations between API/UI shapes (camelCase) and DB shapes (snake_case)
 */

import type {
  PromptScores,
  ApiPromptScores,
  PromptHeuristics,
  ApiHeuristicsData,
} from './database';

/**
 * Convert DB PromptScores (snake_case) to API shape (camelCase)
 */
export function toApiPromptScores(db: PromptScores): ApiPromptScores {
  return {
    clarity: db.clarity_score,
    efficiency: db.efficiency_score,
    context: db.context_score,
    technique: db.technique_score,
    final: db.final_score,
  };
}

/**
 * Convert API PromptScores (camelCase) to DB insert shape (snake_case)
 * Note: Does not include id or created_at (auto-generated by DB)
 */
export function toDbPromptScores(
  api: ApiPromptScores,
  meta: {
    agenticAttemptId: string;
    aiFeedback?: string | null;
    heuristicsData?: PromptHeuristics;
  }
): Omit<PromptScores, 'id' | 'created_at'> {
  return {
    agentic_attempt_id: meta.agenticAttemptId,
    clarity_score: api.clarity,
    efficiency_score: api.efficiency,
    context_score: api.context,
    technique_score: api.technique,
    final_score: api.final,
    ai_feedback: meta.aiFeedback ?? null,
    heuristics_data: meta.heuristicsData ?? {
      total_iterations: 0,
      total_prompt_tokens: 0,
      average_prompt_length: 0,
      techniques_detected: [],
      improvement_between_iterations: false,
      first_attempt_success: false,
    },
  };
}

/**
 * Convert API heuristics (camelCase) to DB shape (snake_case)
 */
export function toDbHeuristics(api: ApiHeuristicsData): PromptHeuristics {
  return {
    total_iterations: api.totalIterations,
    total_prompt_tokens: api.totalPromptTokens,
    average_prompt_length: api.averagePromptLength,
    techniques_detected: api.techniquesDetected,
    improvement_between_iterations: api.improvementBetweenIterations,
    first_attempt_success: api.firstAttemptSuccess,
  };
}

/**
 * Convert DB heuristics (snake_case) to API shape (camelCase)
 */
export function toApiHeuristics(db: PromptHeuristics): ApiHeuristicsData {
  return {
    totalIterations: db.total_iterations,
    totalPromptTokens: db.total_prompt_tokens,
    averagePromptLength: db.average_prompt_length,
    techniquesDetected: db.techniques_detected,
    improvementBetweenIterations: db.improvement_between_iterations,
    firstAttemptSuccess: db.first_attempt_success,
  };
}
